---
- name: Add and remove users
  user:
    name: {{ item.name }}
    state: {{ item.state }}
    shell: {{ item.shell }}
    append: yes
  with_items: {{ users }}

- name: Add SSH Keys for users
  authorized_key:
      user: {{ item.name }}
      key: https://github.com/{{ item.name }}.keys
      exclusive: yes
  with_items: {{ users }}
